---
# tasks file for grafana
- name: Install grafana dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ grafana_dependencies }}"
  when: ansible_os_family == "Debian"

- name: Import grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  when: ansible_os_family == "Debian"

- name: Install grafana
  apt:
    name: grafana
    state: present
  when: ansible_os_family == "Debian"

- name: Start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
