---
# tasks file for grafana
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install grafana dependencies
  apt:
    name: "{{ grafana_dependencies }}"
    state: present
  when: ansible_os_family == "Debian"

- block:
  - name: Import grafana GPG key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
    when: ansible_os_family == "Debian"

  - name: Add grafana repository
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      update_cache: true
    register: _update_apt_cache
    until: _update_apt_cache is succeeded
    retries: 5
    delay: 2
    when: ansible_os_family == "Debian"

  - name: Install grafana
    apt:
      name: "{{ grafana_package }}"
      state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
    when: ansible_os_family == "Debian"

- name: Start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
